# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 777a3ee97148705966113efd3aea4abc27315a30afbf4bc2457588cc525bffd1ea90818c9e378f0dcd165eac64fb3c3d2199e9426dd9df7aaed945a59e89922a

test:
  secret_key_base: 10fe0eba12c2eea573be650789685003747807107b0b04a951f7219fda6adb0ae5024a28d39d8b74793088694b9ef4b73c48d7a7e1dc17e57093ed79adeaf55c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
